name: Build on commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Build workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
